apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "odf.openshift.io/v1alpha1",
          "kind": "StorageSystem",
          "metadata": {
            "name": "ibm-flashsystemcluster-storagesystem",
            "namespace": "openshift-storage"
          },
          "spec": {
            "kind": "flashsystemcluster.odf.ibm.com/v1alpha1",
            "name": "ibm-flashsystemcluster",
            "namespace": "openshift-storage"
          }
        },
        {
          "apiVersion": "odf.openshift.io/v1alpha1",
          "kind": "StorageSystem",
          "metadata": {
            "name": "ocs-storagecluster-storagesystem",
            "namespace": "openshift-storage"
          },
          "spec": {
            "kind": "storagecluster.ocs.openshift.io/v1",
            "name": "ocs-storagecluster",
            "namespace": "openshift-storage"
          }
        }
      ]
    capabilities: Deep Insights
    categories: Storage
    console.openshift.io/plugins: '["odf-console"]'
    containerImage: quay.io/ocs-dev/odf-operator:latest
    description: OpenShift Data Foundation provides a common control plane for storage
      solutions on OpenShift Container Platform.
    olm.skipRange: ""
    operatorframework.io/initialization-resource: |-
      {
        "apiVersion": "odf.openshift.io/v1alpha1",
        "kind": "StorageSystem",
        "metadata": {
          "name": "ocs-storagecluster-storagesystem",
          "namespace": "openshift-storage"
        },
        "spec": {
          "kind": "storagecluster.ocs.openshift.io/v1",
          "name": "ocs-storagecluster",
          "namespace": "openshift-storage"
        }
      }
    operatorframework.io/suggested-namespace: openshift-storage
    operators.operatorframework.io/builder: operator-sdk-v1.13.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/red-hat-storage/odf-operator
    support: Red Hat
    vendors.odf.openshift.io/kind: '["storagecluster.ocs.openshift.io/v1", "flashsystemcluster.odf.ibm.com/v1alpha1"]'
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: odf-operator.v4.9.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StorageSystem is the Schema for the storagesystems API
      displayName: Storage System
      kind: StorageSystem
      name: storagesystems.odf.openshift.io
      resources:
      - kind: FlashSystemCluster
        name: flashsystemclusters.odf.ibm.com
        version: v1alpha1
      - kind: StorageCluster
        name: storageclusters.ocs.openshift.io
        version: v1
      version: v1alpha1
  description: |
    **Red Hat OpenShift Data Foundation** deploys three operators.

    ### OpenShift Data Foundation operator
    The OpenShift Data Foundation operator is the primary operator for
    OpenShift Data Foundation. It serves to facilitate the other operators in
    OpenShift Data Foundation by performing administrative tasks outside their
    scope as well as watching and configuring their CustomResources.

    ### Rook
    [Rook][1] deploys and manages Ceph on OpenShift, which provides block and
    file storage.

    # Core Capabilities
    * **Self-managing service:** No matter which supported storage technologies
    you choose, OpenShift Data Foundation ensures that resources can be
    deployed and managed automatically.

    * **Hyper-scale or hyper-converged:** With OpenShift Data Foundation you
    can either build dedicated storage clusters or hyper-converged clusters
    where your apps run alongside storage.

    * **File, Block, and Object provided by OpenShift Data Foundation:**
    OpenShift Data Foundation integrates Ceph with multiple storage
    presentations including object storage (compatible with S3), block storage,
    and POSIX-compliant shared file system.

    * **Your data, protected:** OpenShift Data Foundation efficiently
    distributes and replicates your data across your cluster to minimize the
    risk of data loss. With snapshots, cloning, and versioning, no more losing
    sleep over your data.

    * **Elastic storage in your datacenter:** Scale is now possible in your
    datacenter. Get started with a few terabytes, and easily scale up.

    * **Simplified data management:** Easily create hybrid and multi-cloud data
    storage for your workloads, using a single namespace.

    [1]: https://rook.io
  displayName: OpenShift Data Foundation
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions/finalizers
          verbs:
          - update
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - '*'
        - apiGroups:
          - console.openshift.io
          resources:
          - consolequickstarts
          verbs:
          - '*'
        - apiGroups:
          - ocs.openshift.io
          resources:
          - storageclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ocs.openshift.io
          resources:
          - storageclusters/finalizers
          verbs:
          - update
        - apiGroups:
          - ocs.openshift.io
          resources:
          - storageclusters/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - odf.ibm.com
          resources:
          - flashsystemclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - odf.openshift.io
          resources:
          - storagesystems
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - odf.openshift.io
          resources:
          - storagesystems/finalizers
          verbs:
          - update
        - apiGroups:
          - odf.openshift.io
          resources:
          - storagesystems/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operators.coreos.com
          resources:
          - catalogsources
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions/finalizers
          verbs:
          - update
        - apiGroups:
          - operators.coreos.com
          resources:
          - installplans
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions/finalizers
          verbs:
          - update
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: odf-operator-controller-manager
      deployments:
      - name: odf-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.9.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --odf-console-port=9001
                command:
                - /manager
                envFrom:
                - configMapRef:
                    name: odf-operator-manager-config
                image: quay.io/ypadia/odf-operator:test
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 300Mi
                  requests:
                    cpu: 200m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: odf-operator-controller-manager
              terminationGracePeriodSeconds: 10
              tolerations:
              - effect: NoSchedule
                key: node.ocs.openshift.io/storage
                operator: Equal
                value: "true"
      - name: odf-console
        spec:
          selector:
            matchLabels:
              app: odf-console
          strategy: {}
          template:
            metadata:
              labels:
                app: odf-console
            spec:
              containers:
              - image: quay.io/ocs-dev/odf-console:latest
                name: odf-console
                ports:
                - containerPort: 9001
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 512Mi
                volumeMounts:
                - mountPath: /var/serving-cert
                  name: odf-console-serving-cert
                  readOnly: true
              tolerations:
              - effect: NoSchedule
                key: node.ocs.openshift.io/storage
                operator: Equal
                value: "true"
              volumes:
              - name: odf-console-serving-cert
                secret:
                  secretName: odf-console-serving-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: odf-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - operator
  - data
  - storage
  links:
  - name: Source Code
    url: https://github.com/red-hat-storage/odf-operator
  maintainers:
  - email: ocs-support@redhat.com
    name: Red Hat Support
  maturity: alpha
  provider:
    name: Red Hat
  version: 4.9.0
