apiVersion: v1
data:
  CSI_ADDONS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  CSI_ADDONS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-storage
  CSI_ADDONS_SUBSCRIPTION_CHANNEL: alpha
  CSI_ADDONS_SUBSCRIPTION_NAME: csi-addons
  CSI_ADDONS_SUBSCRIPTION_PACKAGE: csi-addons
  CSI_ADDONS_SUBSCRIPTION_STARTINGCSV: csi-addons.latest
  IBM_CSI_SUBSCRIPTION_STARTINGCSV: ibm-block-csi-operator.v1.6.0
  IBM_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  IBM_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-storage
  IBM_SUBSCRIPTION_CHANNEL: stable-v1
  IBM_SUBSCRIPTION_NAME: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_PACKAGE: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_STARTINGCSV: ibm-storage-odf-operator.v1.0.0
  NOOBAA_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  NOOBAA_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-storage
  NOOBAA_SUBSCRIPTION_CHANNEL: alpha
  NOOBAA_SUBSCRIPTION_NAME: noobaa-operator
  NOOBAA_SUBSCRIPTION_PACKAGE: noobaa-operator
  NOOBAA_SUBSCRIPTION_STARTINGCSV: noobaa-operator.v5.9.0
  OCS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  OCS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-storage
  OCS_SUBSCRIPTION_CHANNEL: alpha
  OCS_SUBSCRIPTION_NAME: ocs-operator
  OCS_SUBSCRIPTION_PACKAGE: ocs-operator
  OCS_SUBSCRIPTION_STARTINGCSV: ocs-operator.v4.9.0
  ODF_SUBSCRIPTION_NAME: odf-operator
  ODF_SUBSCRIPTION_STARTINGCSV: odf-operator.v4.9.0
  OPERATOR_NAMESPACE: openshift-storage
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: 4fd470de.openshift.io
kind: ConfigMap
metadata:
  name: odf-operator-manager-config
